"""High-level tools for practical tasks like research and PPT creation."""

from __future__ import annotations

import os
import re
import textwrap
from datetime import datetime
from pathlib import Path

import feedparser
from pptx import Presentation


class TaskTools:
    """Utilities NOVA can call for real-world tasks."""

    @staticmethod
    def create_ppt(topic: str, output_dir: str | None = None) -> str:
        clean_topic = topic.strip() or "Untitled Topic"
        slug = re.sub(r"[^a-zA-Z0-9]+", "-", clean_topic).strip("-").lower()

        base_dir = Path(output_dir or Path.home() / "Documents" / "nova_outputs")
        base_dir.mkdir(parents=True, exist_ok=True)
        file_path = base_dir / f"{slug or 'presentation'}-{datetime.now().strftime('%Y%m%d-%H%M%S')}.pptx"

        prs = Presentation()
        title_slide = prs.slides.add_slide(prs.slide_layouts[0])
        title_slide.shapes.title.text = clean_topic
        title_slide.placeholders[1].text = "Generated by NOVA"

        outline = [
            "Overview",
            "Why this matters",
            "Current trends",
            "Action plan",
            "Next steps",
        ]

        for section in outline:
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = section
            body = slide.shapes.placeholders[1].text_frame
            bullets = TaskTools._section_bullets(clean_topic, section)
            body.text = bullets[0]
            for bullet in bullets[1:]:
                p = body.add_paragraph()
                p.text = bullet

        prs.save(file_path)
        return str(file_path)

    @staticmethod
    def get_headlines(limit: int = 5) -> list[str]:
        feed_url = "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
        feed = feedparser.parse(feed_url)
        headlines: list[str] = []
        for entry in feed.entries[:limit]:
            title = getattr(entry, "title", "").strip()
            if title:
                headlines.append(textwrap.shorten(title, width=120, placeholder="..."))
        return headlines

    @staticmethod
    def quick_research_brief(topic: str) -> str:
        prompt = topic.strip() or "general research"
        return (
            f"Research workflow for '{prompt}': define objective, gather 3-5 high-quality sources, "
            "extract key evidence, compare viewpoints, and produce a concise summary with citations."
        )